from Manufacture.products.products_center_st import TestProductsCenterTable
from Manufacture.marketing_contact.marketing_contact_products_st import TestMarketingContactProducts
from Manufacture.home.new_center_st import TestNewCenter
from Manufacture.about.about_table_st import TestAboutUs
from Manufacture.marketing.marketing_st import TestMarketing
from Manufacture.products.module_in_info_st import InModuleInfo
from Manufacture.technology.technology_table_st import TestTechnologyTable
from Manufacture.marketing_contact.marketing_contact_about_st import TestMarketingContactAbout
from Manufacture.contact.contact_st import TestContact
from Manufacture.marketing_contact.marketing_contact_news_st import TestMarketingContactNews
from Manufacture.news.company_news_st import TestCompanyNewsTable
from Manufacture.home.about_us_st import TestHome
from Manufacture.news.news_table_st import TestNewsTable


__all__ = {TestMarketing, TestMarketingContactAbout, TestNewCenter, TestTechnologyTable, TestMarketingContactNews, TestCompanyNewsTable, TestProductsCenterTable, TestMarketingContactProducts, TestContact, TestHome, TestNewsTable, InModuleInfo, TestAboutUs}